### ISSUE TITLE
Inconsistent behaviour in highlights

### ISSUE THREAD

**Issue by ravisumit33** [uyha/tree-sitter-cmake#2]
I am facing inconsistent behaviour in cmake highlights when using tree-sitter. Colors of options seem turning on/off when I scroll and sometimes I endup like below:

<img width="367" alt="Screenshot 2021-09-19 at 9 34 07 PM" src="https://user-images.githubusercontent.com/19284116/133934503-4cc1ca3e-1473-4795-804b-fd020e5be63d.png">

You can see clearly one option is highlighted while other one is not. Is it a known issue ?

**Comment by uyha** [comment]
I think this is a bug of my highlights query in `nvim-treesitter`, I'll try to fix it today

**Comment by uyha** [comment]
I also see the color turning on/off and I think that's a bug with `nvim-treesitter`, but i didn't spend time to investigate it

**Comment by ravisumit33** [comment]
I use `nvim-treesitter` for different languages like C/C++, python, javascript etc. but didn't find color turning on/off in them. Its only coming in cmake files.

**Comment by uyha** [comment]
do you have some small example i can you to test?

**Comment by ravisumit33** [comment]
```
project (sample)
cmake_minimum_required(VERSION 3.20)
set(CMAKE_EXPORT_COMPILE_COMMANDS 1)
add_executable(sample sample.cpp)
target_compile_options(sample
PUBLIC
  -v)
```

**Comment by ravisumit33** [comment]
Color of `PUBLIC` changes everytime when I click on it or scroll.

**Comment by uyha** [comment]
that's weird because my parser doesn't do anything special about the command `target_compile_options` and neither does my highlights query. Anyway, i'll check it out.

**Comment by ravisumit33** [comment]
@uyha Any update on this?

**Comment by uyha** [comment]
I'm holidays now so I won't have a look at this until the weekends. I will start diving in after my holidays

**Comment by uyha** [comment]
should be fixed when using nightly nvim
