### ISSUE TITLE
some parse error finded from opencv

### ISSUE THREAD

**Issue by Decodetalkers** [uyha/tree-sitter-cmake#26]
```cmake
if(dep MATCHES "^\\$<LINK_ONLY:([^>]+)>$")
       set(dep "${CMAKE_MATCH_1}")
 endif()
if(dep MATCHES "^\\$<")
       message(WARNING "Unexpected CMake generator expression: ${dep}")
endif()
```

https://github.com/opencv/opencv/blob/4.x/cmake/OpenCVUtils.cmake#L1705 it if from this file , and error part is the snippet above

**Comment by uyha** [comment]
yup, i see the problem, I will try to fix it today

**Comment by uyha** [comment]
fixed now by removing `gen_exp` (checkout the commit for more details why).

**Comment by Decodetalkers** [comment]
thanks
