### ISSUE TITLE
The binding of cmake cannot be used

### ISSUE THREAD

**Issue by Decodetalkers** [uyha/tree-sitter-cmake#4]
I run cargo test, however failed, report link error. I know little about treesitter and cannot find what happened.

**Comment by Decodetalkers** [comment]
and after I remove the src of the repo, re generate the cmake , it cannot parse any of my code

**Comment by Decodetalkers** [comment]
I think the gammer is broken

**Comment by uyha** [comment]
could you provide the commands you ran and their output?

**Comment by Decodetalkers** [comment]
> could you provide the commands you ran and their output?

First, I clean the src and binding under the repo

```bash
rm -rf src
rm -rf bindings
rm -rf Cargo.toml
```
Then I regenerate the repo
```bash
tree-sitter generate
```
and run the parse

```bash
tree-sitter parse CMakeList.txt
```

output is 
```
Failed to load language in current directory

Caused by:
    0: Error opening dynamic library "/home/cht/.cache/tree-sitter/lib/cmake.so"
    1: /home/cht/.cache/tree-sitter/lib/cmake.so: undefined symbol: tree_sitter_cmake_external_scanner_create
```
and Run the cargo test

```
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by Decodetalkers** [comment]
The parse generated by tree-sitter is different with the src under the repo .Maybe tree-sitter has updated?

**Comment by Decodetalkers** [comment]
Any update now?

**Comment by uyha** [comment]
I’m on vacation now so I will take a look later

**Comment by Decodetalkers** [comment]
I found out what happened , it is the line of externals

**Comment by Decodetalkers** [comment]
Maybe the external session is broken in tree-sitter?

**Comment by Decodetalkers** [comment]
Yes ,it is depreated... Finally found out what happened

**Comment by Decodetalkers** [comment]
Sorry , I miss the scanner.cc

**Comment by Decodetalkers** [comment]
My problem ,sorry
